show_avatars:
  default: "none"
  type: enum
  choices:
    - all
    - none
    - topics
    - messages
  description:
    en: Display excerpt avatar.
show_reply_icon:
  default: "none"
  type: enum
  choices:
    - all
    - none
    - topics
    - messages
  description:
    en: Display a reply icon before latest post excerpt.
single_line:
  default: false
  description:
    en: Apply styling to limit excerpt to a single line.
categories:
  type: list
  default: ""
  list_type: category
  description:
    en: Apply plugin to the following categories.
private_messages:
  default: false
  type: bool
  description:
    en: Apply plugin to private messages